services:
  tonies-discord-bot:
    build: .
    container_name: tonies-discord-bot
    environment:
      - CLIENT_CERT_PATH=certs/client.crt
      - CLIENT_KEY_PATH=certs/client.key
      - DISCORD_AUTHOR=
      - DISCORD_TOKEN=
      - DISCORD_DELETE_ORIGIN_MESSAGE=false
      - JSON_URL=https://raw.githubusercontent.com/toniebox-reverse-engineering/tonies-json/release/toniesV2.json
      - LOG_LEVEL=INFO
      - TEDDYCLOUD_API=
      - TEDDYCLOUD_AUTO_ADD_TONIES=false
    restart: unless-stopped
    volumes:
      - ./app/certs:/app/certs
