# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tafHeader.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'tafHeader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftafHeader.proto\"\xdc\x01\n\x17TonieboxAudioFileHeader\x12\x11\n\tsha1_hash\x18\x01 \x02(\x0c\x12\x11\n\tnum_bytes\x18\x02 \x02(\x04\x12\x10\n\x08\x61udio_id\x18\x03 \x02(\r\x12\x1b\n\x0ftrack_page_nums\x18\x04 \x03(\rB\x02\x10\x01\x12\r\n\x05_fill\x18\x05 \x02(\x0c\x12\x1c\n\x14ogg_granule_position\x18\x06 \x01(\x04\x12\x18\n\x10ogg_packet_count\x18\x07 \x01(\x04\x12\x15\n\rtaf_block_num\x18\x08 \x01(\x04\x12\x0e\n\x06pageno\x18\t \x01(\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tafHeader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TONIEBOXAUDIOFILEHEADER'].fields_by_name['track_page_nums']._loaded_options = None
  _globals['_TONIEBOXAUDIOFILEHEADER'].fields_by_name['track_page_nums']._serialized_options = b'\020\001'
  _globals['_TONIEBOXAUDIOFILEHEADER']._serialized_start=20
  _globals['_TONIEBOXAUDIOFILEHEADER']._serialized_end=240
# @@protoc_insertion_point(module_scope)
